Adding tests for timetracker
- Many tests added
- Some logic changes shown by tests
- A few shellcheck fixes

diff --git a/actions/timetracker/timetracker b/actions/timetracker/timetracker
--- a/actions/timetracker/timetracker
+++ b/actions/timetracker/timetracker
@@ -6,65 +6,17 @@
 # License:  GPL, http://www.gnu.org/copyleft/gpl.html
 
 usage() {
-	echo "$(basename "${0}") on|off|list|archive|unarchive|stats [project]"
-	echo "	Track time spent on a project."
+	echo "    $(basename "${0}") on|off|list|archive|unarchive|stats|archivedstats|statsall [project]"
+	echo "      Track time spent on a project."
+}
+
+die () {
+  [[ -f "${TODO_TMP_FILE}" ]] && rm -rf "${TODO_TMP_FILE}"
 	exit 1
 }
 
-# Setup some variables
-PRE=$(basename "${TODO_FILE}" | sed 's/.txt$//g')
-CURRENT=$(find "${TODO_DIR}/tt/${PRE}/" -maxdepth 1 -name "*.tt" | awk -F / '{print $NF}' | sed 's/\.tt$//' | sort)
-ARCHIVED=$(find "${TODO_DIR}/tt/${PRE}/archive/" -maxdepth 1 -name "*.tt" | awk -F / '{print $NF}' | sed 's/\.tt$//' | sort)
-shift; action=$1
-# If we are getting stats, allow blank project
-if [ -z "${2}" ]; then
-	if [ $(echo "${action}" | grep -c 'list\|stats') -eq 1 ]; then
-		ALL=1
-	fi
-	if [ "$(echo "${action}" | grep -c 'list\|stats')" -eq 0 ]; then
-		usage
-	fi
-else
-	# Remove + from project
-	project=$(echo "${2}" | sed 's/^\+//g')
-	ALL=0
-fi
-
-# Human style timings
-tthuman () {
-	TOTAL=$1
-	RUNNING=$2
-	DAYS=$((${TOTAL}/86400))
-	if [ ${DAYS} -gt 0 ]; then
-		TEXTDAYS="${DAYS} days "
-	else
-		TEXTDAYS=""
-	fi
-	REMOVEDAYS=$((${TOTAL}-${DAYS}*86400))
-	HOURS=$(($REMOVEDAYS/3600))
-	if [ ${HOURS} -gt 0 ]; then
-		TEXTHOURS="${HOURS} hours "
-	else
-		TEXTHOURS=""
-	fi
-	REMOVEHOURS=$(($REMOVEDAYS-${HOURS}*3600))
-	MINUTES=$(($REMOVEHOURS/60))
-	if [ ${MINUTES} -gt 0 ]; then
-		TEXTMINUTES="${MINUTES} minutes "
-	else
-		TEXTMINUTES=""
-	fi
-		SECONDS=$(($REMOVEHOURS-${MINUTES}*60))
-	if [ ${SECONDS} -gt 0 ]; then
-		TEXTSECONDS="${SECONDS} seconds "
-	else
-		TEXTSECONDS=""
-	fi
-}
-
-
-# Make directories that may be needed
 ttprep() {
+	# Make directories that may be needed
 	if [ ! -d "${TODO_DIR}/tt/${PRE}/" ]; then
 		mkdir -p "${TODO_DIR}/tt/${PRE}"
 	fi
@@ -74,49 +26,148 @@ ttprep() {
 }
 
 tttests () {
-	if [ "$(grep -c "\+${project}" "$TODO_FILE")" -lt 1 ]; then
-		echo ""
-		echo "Project doesn't appear in the todo.txt file, exiting"
-		echo ""
-		exit 1
+	# If we are getting stats, allow blank project
+	if [[ -z "${1}" ]]; then
+		if [[ $(echo "${action}" | grep -c 'list\|stats') -eq 1 ]]; then
+			ALL=1
+		elif [[ "$(echo "${action}" | grep -c 'list\|stats')" -eq 0 ]]; then
+			usage
+			echo "      No project given"
+			die
+		fi
+	else
+		# Remove + from project
+		project="${1/#+/}"
+		ALL=0
+	fi
+}
+
+_start () {
+	# if tt file doesn't exist start
+	if ! [[ -f "${TODO_DIR}/tt/${PRE}/${project}.tt" ]]; then
+		echo "$(date +"%s")" >> "${TODO_DIR}/tt/${PRE}/${project}.tt"
+		echo "${1}"
+		exit
+	fi
+	# If project file exists and if our last line has only two fields, then add time stamp
+	if [ "$(tail -1 "${TODO_DIR}/tt/${PRE}/${project}.tt" | grep -c :)" -eq 1 ] ; then
+		echo "$(date +"%s")" >> "${TODO_DIR}/tt/${PRE}/${project}.tt"
+		echo "${1}"
+		exit
+	# Else the timer is still active
+	else
+		usage
+		echo "      Project ${project} is still active, cannot turn on the clock"
+		die
+	fi
+}
+
+_stop () {
+	set +x
+	# Remove the state and set File location
+	STATE=$1; shift
+	if [[ "${STATE}" = "live" ]]; then
+		FILE="${TODO_DIR}/tt/${PRE}/${project}"
+	elif [[ "${STATE}" = "archived" ]]; then
+		FILE="${TODO_DIR}/tt/${PRE}/archive/${project}"
+	fi
+	# Get start from last line of project tt file
+	START=$(tail -1 "${FILE}.tt")
+	# Current time
+	END="$(date +"%s")"
+	# Print all but last line, then start and end into temp file
+	head -n -1 "${FILE}.tt"; echo "${START}:${END}" > "${FILE}.tmp"
+	mv "${FILE}.tmp" "${FILE}.tt"
+	echo "${1}"
+	exit
+}
+
+# Usage for todo.sh help or remove action
+# Remove todo.txt action name
+if [[ "${2}" =~ (usage|help|--help) ]]; then
+	usage
+	die
+elif [[ "${1}" = "$(basename "$0")" ]]; then
+  shift
+  action=$1
+  shift
+fi
+
+# Setup some variables
+PRE=$(basename "${TODO_FILE}" | sed 's/.txt$//g')
+
+# Run our prep and tests
+ttprep
+tttests "$@"
+
+# Setup some variables
+CURRENT=$(find "${TODO_DIR}/tt/${PRE}/" -maxdepth 1 -name "*.tt" | awk -F / '{print $NF}' | sed 's/\.tt$//' | sort)
+ARCHIVED=$(find "${TODO_DIR}/tt/${PRE}/archive/" -maxdepth 1 -name "*.tt" | awk -F / '{print $NF}' | sed 's/\.tt$//' | sort)
+
+# Human style timings
+tthuman () {
+	TOTAL=$1
+	RUNNING=$2
+	DAYS=$((TOTAL / 86400))
+	if [[ "${DAYS}" -gt 0 ]]; then
+		TEXTDAYS="${DAYS} days "
+	else
+		TEXTDAYS=""
+	fi
+	# shellcheck disable=SC2034,SC2035
+	REMOVEDAYS=$((TOTAL - DAYS * 86400))
+	HOURS=$((REMOVEDAYS / 3600))
+	if [ "${HOURS}" -gt 0 ]; then
+		TEXTHOURS="${HOURS} hours "
+	else
+		TEXTHOURS=""
+	fi
+	# shellcheck disable=SC2034,SC2035
+	REMOVEHOURS=$((REMOVEDAYS - HOURS * 3600))
+	MINUTES=$((REMOVEHOURS / 60))
+	if [[ "${MINUTES}" -gt 0 ]]; then
+		TEXTMINUTES="${MINUTES} minutes "
+	else
+		TEXTMINUTES=""
+	fi
+	# shellcheck disable=SC2034,SC2035
+		SECONDS=$((REMOVEHOURS - MINUTES * 60))
+	if [[ "${SECONDS}" -gt 0 ]]; then
+		TEXTSECONDS="${SECONDS} seconds "
+	else
+		TEXTSECONDS=""
 	fi
 }
 
 # Archive the project tt file
 ttarchive() {
+	project="${1/#+/}"
 	if [ -f "${TODO_DIR}/tt/${PRE}/${project}.tt" ]; then
 		if [ "$(tail -1 "${TODO_DIR}/tt/${PRE}/${project}.tt" | grep -c :)" -eq 0 ]; then
 			echo "$(cat "${TODO_DIR}/tt/${PRE}/${project}.tt"):$(date +%s)" >> "${TODO_DIR}/tt/${PRE}/archive/${project}.tt"
 			rm "${TODO_DIR}/tt/${PRE}/${project}.tt" 
-			echo ""
-			echo "Setting ${project} as finished now and archiving"
-			echo ""
+			echo "Setting project ${project} as finished now and archiving"
 		else
 			mv "${TODO_DIR}/tt/${PRE}/${project}.tt" "${TODO_DIR}/tt/${PRE}/archive/"
-			echo ""
-			echo "Archiving ${project}"
-			echo ""
+			echo "Archived ${project}"
 		fi
 	else
-		echo ""
-		echo "Project ${project} does not exist"
-		echo ""
+		usage
+		echo "      Project ${project} does not exist"
+		die
 	fi
 }
 
 ttunarchive () {
-	echo ""
+	project="${1/#+/}"
 	if [ -f "${TODO_DIR}/tt/${PRE}/archive/${project}.tt" ]; then
-		if [ ! -f "${TODO_DIR}/tt/${PRE}/${project}.tt" ]; then
-			mv "${TODO_DIR}/tt/${PRE}/archive/${project}.tt" "${TODO_DIR}/tt/${PRE}/${project}.tt"
-			echo "Project ${project} unarchived"
-		else
-			echo "Project ${project} is current, will not unarchive"
-		fi
+		mv "${TODO_DIR}/tt/${PRE}/archive/${project}.tt" "${TODO_DIR}/tt/${PRE}/${project}.tt"
+		echo "Project ${project} unarchived"
 	else
-		echo "Project ${project} not archived, cannot unarchive"
+		usage
+		echo "      Project ${project} not archived"
+		die
 	fi
-	echo ""
 }
 
 ttlist () {
@@ -135,6 +186,10 @@ ttlist () {
 			echo "$ARCHIVED"
 			echo ""
 		fi
+	else
+		usage
+		echo "      No files to list"
+		die
 	fi
 }
 
@@ -147,181 +202,183 @@ ttsimplearchivedlist () {
 }
 
 ttsimplelistall () {
-    echo "${CURRENT} ${ARCHIVED}"
+    echo "${CURRENT}"
+		echo "${ARCHIVED}"
 }
 
 tton() {
-	if [ -f "${TODO_DIR}/tt/${PRE}/${project}.tt" ]; then
-		# If project file exists and if our last line has only one field, then add time stamp
-		if [ "$(tail -1 "${TODO_DIR}/tt/${PRE}/${project}.tt" | grep -c :)" -eq 1 ] ; then
-			echo "$(date +"%s")" >> "${TODO_DIR}/tt/${PRE}/${project}.tt"
-			echo ""
-			echo "Starting clock on ${project}"
-			echo ""
-		else
-			echo ""
-			echo "Project ${project} is still active, cannot turn on the clock"
-			echo ""
+	project="${1/#+/}"
+	# if project is in todo.txt
+	if [[ $(grep -c "+${project}" "${TODO_FILE}") -gt 0 ]]; then
+		# if project tt file exists
+		if [[ -f "${TODO_DIR}/tt/${PRE}/${project}.tt" ]]; then
+			_start "Starting clock on ${project}"
+		# if project tt archivefile exists
+		elif [[ -f "${TODO_DIR}/tt/${PRE}/archive/${project}.tt" ]]; then
+			echo "Project ${project} is archived, unarchive?"
+			read -r -n1 -p "(y/n)"
+			[[ $REPLY = [yY] ]] && mv "${TODO_DIR}/tt/${PRE}/archive/${project}.tt" "${TODO_DIR}/tt/${PRE}/${project}.tt" || { echo "Not unarchiving"; exit 1; }
+			_start "Unarchiving and starting clock on ${project}"
 		fi
-	# If project file doesn't exist add initial time stamp
+		# if no tt file exits, start one
+		_start "Starting clock on ${project}"
+	# if project is not in todo.txt
 	else
-			# if Project is archived, ask to unarchive, then start clock
-			if [ -f "${TODO_DIR}/tt/${PRE}/archive/${project}.tt" ]; then
-					echo "Project ${project} is archived, unarchive?"
-					read -n1 -p "(y/n)"
-					[[ $REPLY = [yY] ]] && mv "${TODO_DIR}/tt/${PRE}/archive/${project}.tt" "${TODO_DIR}/tt/${PRE}/${project}.tt" || { echo "Okay, exiting"; exit 1; }
-					echo "$(date +"%s")" >> "${TODO_DIR}/tt/${PRE}/${project}.tt"
-					echo ""
-					echo "Unarchiving and starting clock on ${project}"
-					echo ""
-			# Project doesn't exist, create and start project
-			else
-					echo "$(date +"%s")" >> "${TODO_DIR}/tt/${PRE}/${project}.tt"
-					echo ""
-					echo "Starting clock on ${project}"
-					echo ""
-			fi
+		usage
+		echo "      Project ${project} is not in todo.txt"
+		die
 	fi
 }
 
 ttoff() {
-	if [ -f "${TODO_DIR}/tt/${PRE}/${project}.tt" ]; then
-		# if our last line has one field, then add the finish time
-		if [ "$(tail -1 "${TODO_DIR}/tt/${PRE}/${project}.tt" | grep -c :)" -eq 0 ] ; then
-			echo "$(tail -1 "${TODO_DIR}/tt/${PRE}/${project}.tt" | tr -d '\n'):$(date +"%s")" >> "${TODO_DIR}/tt/${PRE}/${project}.tmp"
-			sed -i '$d' "${TODO_DIR}/tt/${PRE}/${project}.tt"
-			cat "${TODO_DIR}/tt/${PRE}/${project}.tmp" >> "${TODO_DIR}/tt/${PRE}/${project}.tt"
-			rm -rf "${TODO_DIR}/tt/${PRE}/${project}.tmp"
-			echo ""
-			echo "Stopping clock on ${project}"
-			echo ""
-		else
-			if [ ! -s "${TODO_DIR}/tt/${PRE}/${project}.tt" ]; then
-				echo "${project} is new, use $(basename "$0") on first"
-			else
-				echo "Project ${project} is not active, cannot turn off the clock"
-			fi
-		fi
-else
-		echo ""
-		echo "Project ${project} does not exist"
-		echo ""
+	project="${1/#+/}"
+	FILE="${TODO_DIR}/tt/${PRE}/${project}.tt"
+	ARCHIVE="${TODO_DIR}/tt/${PRE}/archive/${project}.tt"
+	# if project has a tt file started
+	if [[ -f "${FILE}" ]] && [[ "$(tail -1 "${FILE}" | grep -c :)" -eq 0 ]] ; then
+		_stop live "Stopping clock on ${project}"
+	# if project has an archived tt file started
+	elif [[ -f "${ARCHIVE}" ]] && [[ "$(tail -1 "${ARCHIVE}" | grep -c :)" -eq 0 ]] ; then
+		_stop archived "Stopping clock on ${project} which is archived"
+	# if project has neither tt file or archive file started
+	elif [[ (-f "${FILE}" && "$(tail -1 "${FILE}" | grep -c :)" -eq 1 ) ]] && [[ (-f "${ARCHIVE}" && "$(tail -1 "${ARCHIVE}" | grep -c :)" -eq 1) ]]; then
+		usage
+		echo "      Project ${project} is not active"
+		die
+	# if project is not in todo.txt file
+	elif [[ "$(grep -c "${project}" "${TODO_FILE}")" -eq 0  ]]; then
+		usage
+		echo "      Project ${project} does not exist in todo.txt"
+		die
+	# if project has no tt file nor archive file
+	elif [[ ! -f "${TODO_DIR}/tt/${PRE}/${project}.tt"  ]] && [[ ! -f "${TODO_DIR}/tt/${PRE}/archive/${project}.tt" ]]; then
+		usage
+		echo "      No sign of tt file for project ${project}"
+		die
 	fi
 }
 
 # Show the stats for the project
 ttstats() {
+	project="${1/#+/}"
 	if [ -f "${TODO_DIR}/tt/${PRE}/${project}.tt" ]; then
 		if [ "$(tail -1 "${TODO_DIR}/tt/${PRE}/${project}.tt" | grep -c :)" -eq 0 ]; then
-			TOTAL=$(echo $(cat ${TODO_DIR}/tt/${PRE}/${project}.tt):$(date +%s) |awk -F ':' '{print $2 - $1}' | awk '{ sum+=$1} END {print sum}')
+			TOTAL=$(echo $(cat "${TODO_DIR}/tt/${PRE}/${project}.tt"):$(date +%s) |awk -F ':' '{print $2 - $1}' | awk '{ sum+=$1} END {print sum}')
 			RUNNING=1
 		else
-			TOTAL=$(echo "$(cat ${TODO_DIR}/tt/${PRE}/${project}.tt)" |awk -F ':' '{print $2 - $1}' | awk '{ sum+=$1} END {print sum}')
+			TOTAL=$(echo "$(cat "${TODO_DIR}/tt/${PRE}/${project}.tt")" |awk -F ':' '{print $2 - $1}' | awk '{ sum+=$1} END {print sum}')
 			RUNNING=0
 		fi
-		tthuman ${TOTAL} ${RUNNING}
-		echo ""
+		tthuman "${TOTAL}" "${RUNNING}"
 		echo "Stats for Project: ${project}"
 		CHAR=$(echo "Stats for Project: ${project}"| sed 's/./=/g')
-		echo $CHAR
+		echo "${CHAR}"
 		if [ ${RUNNING} -eq 1 ]; then
 			echo "Timer still running for ${project}"
 		fi
-		echo ""
 		echo "${TEXTDAYS}${TEXTHOURS}${TEXTMINUTES}${TEXTSECONDS}"
-			echo ""
 	else
-			echo ""
-			echo "Project ${project} does not exist"
-			echo ""
+		usage
+		echo "      No current timetracker projects"
+		die
 	fi
 }
 
 ttarchivedstats () {
+	project="${1/#+/}"
 	if [ -f "${TODO_DIR}/tt/${PRE}/archive/${project}.tt" ]; then
-		TOTAL="$(cat "${TODO_DIR}/tt/${PRE}/archive/${project}.tt" |awk -F ':' '{print $2 - $1}' | awk '{ sum+=$1} END {print sum}')"
-		RUNNING=0
-		
+		if [ "$(tail -1 "${TODO_DIR}/tt/${PRE}/archive/${project}.tt" | grep -c :)" -eq 0 ]; then
+			TOTAL=$(echo $(cat "${TODO_DIR}/tt/${PRE}/archive/${project}.tt"):$(date +%s) |awk -F ':' '{print $2 - $1}' | awk '{ sum+=$1} END {print sum}')
+			RUNNING=1
+		else
+			TOTAL=$(echo "$(cat "${TODO_DIR}/tt/${PRE}/archive/${project}.tt")" |awk -F ':' '{print $2 - $1}' | awk '{ sum+=$1} END {print sum}')
+			RUNNING=0
+		fi
 			tthuman "${TOTAL}" "${RUNNING}"
-
-			echo ""
 		echo "Stats for archived Project: ${project}"
-			CHAR=$(echo "Stats for archived Project: ${project}"| sed 's/./=/g')
-			echo "${CHAR}"
-		echo ""
+		CHAR=$(echo "Stats for archived Project: ${project}"| sed 's/./=/g')
+		echo "${CHAR}"
+		if [ ${RUNNING} -eq 1 ]; then
+			echo "Timer still running for ${project}"
+		fi
 		echo "${TEXTDAYS}${TEXTHOURS}${TEXTMINUTES}${TEXTSECONDS}"
-			echo ""
 	else
-			echo ""
-			echo "Project ${project} does not exist"
-			echo ""
+		usage
+		echo "      No current timetracker projects"
+		die
 	fi
 }
 
 # Main
-ttprep
-tttests
 case "${action}" in
 	stats)
 		# If no project was set, show all projects stats
 		if [ ${ALL} -eq 1 ]; then
+			if [[ "$(find "${TODO_DIR}/tt/${PRE}/" -type f -name "*.tt" | wc -l)" -eq 0 ]]; then
+				usage
+				echo "      No timetracker projects exist"
+				die
+			fi
 			cd "${TODO_DIR}/tt/${PRE}/" || exit 1
 			for project in *.tt; do
-				project="$(echo "${project}" | sed 's/\.tt$//')"
-				ttstats "${project}"
+				project="${project/#+/}"
+				ttstats "${@}"
 			done
 		else
-			ttstats
+			ttstats "${@}"
 		fi
 	;;
 	archivedstats)
 		# If no project was set, show all projects stats
 		if [ ${ALL} -eq 1 ]; then
-			cd "${TODO_DIR}/tt/${PRE}/archive"
+			if [[ "$(find "${TODO_DIR}/tt/${PRE}/archive/" -type f -name "*.tt" | wc -l)" -eq 0 ]]; then
+				usage
+				echo "      No timetracker projects exist"
+				die
+			fi
+			cd "${TODO_DIR}/tt/${PRE}/archive" || exit 1
 			for project in *.tt; do
-				project="$(echo "${project}" | sed 's/\.tt$//')"
+				project="${project/#+/}"
 				ttarchivedstats "${project}"
 			done
 		else
-			ttarchivedstats
+			ttarchivedstats "${@}"
 		fi
 	;;
 	statsall)
-		# If no project was set, show all projects stats
-		if [ ${ALL} -eq 1 ]; then
-				cd "${TODO_DIR}/tt/${PRE}/"
-				for project in *.tt; do
-						project="$(echo "${project}" | sed 's/\.tt$//')"
-						ttstats "${project}"
-				done
-		else
-				ttstats
+		# If we have not projects, error out
+		if [[ -z "${CURRENT}" ]] && [[ -z "${ARCHIVED}" ]]; then
+			usage
+			echo "      No timetracker projects exist"
+			die
 		fi
-		# If no project was set, show all projects stats
-		if [ ${ALL} -eq 1 ]; then
-			cd "${TODO_DIR}/tt/${PRE}/archive"
-			for project in *.tt; do
-				project="$(echo "${project}" | sed 's/\.tt$//')"
+		# If we have current projects
+		if [[ -n "${CURRENT}" ]]; then
+			for project in $(ttsimplelist); do
+				ttstats "${project}"
+			done
+		fi
+		# If we have archived projects
+		if [[ -n "${ARCHIVED}" ]]; then
+			for project in $(ttsimplearchivedlist); do
 				ttarchivedstats "${project}"
 			done
-		else
-			ttarchivedstats
 		fi
 	;;
 	on)
-		tton
+		tton "$@"
 	;;
 	off)
-		ttoff
+		ttoff "$@"
 	;;
 	list)
 		ttlist
 	;;
 	archive)
-		ttarchive
+		ttarchive "$@"
 	;;
 	unarchive)
-		ttunarchive
+		ttunarchive "$@"
 	;;
 	simplelist)
 		ttsimplelist
