Various Fixes and Logic improvements for misc actions
- Check before cleanup of TODO_TMP_FILE
- Better Usage everywhere
- Bash only notes, enotes, context and project cleanup
- Use of die function over echo, usage and exit
- Move to checking for empty and non-empty variables over starting with
  zero
- Remove some seds for bash search and replace
- Moved to listcon listprj builtins

diff --git a/actions/projectview/projectview b/actions/projectview/projectview
--- a/actions/projectview/projectview
+++ b/actions/projectview/projectview
@@ -35,7 +35,6 @@ elif [[ "${1}" = "$(basename "$0")" ]]; then
   shift
 fi
 
-## Variables
 # Limit to show requested projects
 PROJECT_LIMIT=0
 # Check how we are being run
@@ -67,47 +66,45 @@ export TODOTXT_DISABLE_FILTER=1
 
 # Eat the remaining arguments putting them into context or terms variables
 while [[ $# -gt 0 ]]; do
-	if [[ $(echo "$1" | grep -c "+\w") -eq 1 ]]; then
-    # shellcheck disable=SC2001
-		PROJECTS="${PROJECTS} $(echo "$1" | sed 's/^+//g')"; shift
-    # shellcheck disable=SC2001
-    PROJECTS="$(echo "${PROJECTS}" | sed 's/^ //g')"
+  if [[ $(grep -c "+\w" <<< "$1") -eq 1 ]]; then
+    PROJECTS="${1/#+/}"; shift
 		PROJECT_LIMIT=1
 	else
-		TERMS="${TERMS} $(echo "$1" | cut -d ' ' -f 1)"; shift
-    # shellcheck disable=SC2001
-    TERMS="$(echo "${TERMS}" | sed 's/^ //g')"
+    TERMS="$(echo "$1" | cut -d ' ' -f 1)"; shift
 	fi
 done
 
-# If we have no valid terms or projects error out
+# If we have non-valid projects error out
 for project in ${PROJECTS}; do
-  OLD_TODOTXT_VERBOSE=${TODOTXT_VERBOSE:-1}
-  TODOTXT_VERBOSE=0 VALID_PROJECT=$(_list "${TODO_FILE}" "+${project}" "${TERMS}" | wc -l)
-  TODOTXT_VERBOSE=${OLD_TODOTXT_VERBOSE}
-  if [[ "${VALID_PROJECT}" -eq 0 ]]; then
-    echo "      \"${TERMS} \" not found in project +${project} in todo.txt"
+  if ! [[ $(grep -c "${project}" "${TODO_FILE}") -gt 0  ]]; then
+    die "      project \"${project}\" not found in todo.txt"
+  fi
+done
+
+# if we have terms not in todo.txt error
+OLD_TODOTXT_VERBOSE=${TODOTXT_VERBOSE:-1}
+TODOTXT_VERBOSE=0 VALID_TERM=$(_list "${TODO_FILE}" "" "${TERMS}" | wc -l)
+TODOTXT_VERBOSE=${OLD_TODOTXT_VERBOSE}
+if [[ "${VALID_TERM}" -eq 0 ]]; then
+  die "      \"${TERMS}\" not found in todo.txt"
+fi
+
+# If we have no valid terms in valid projects error out
+for project in ${PROJECTS}; do
+  # OLD_TODOTXT_VERBOSE=${TODOTXT_VERBOSE:-1}
+  # TODOTXT_VERBOSE=0 VALID_TERM=$(_list "${TODO_FILE}" "" "${TERMS}" | wc -l)
+  VALID_TERM=$(grep "${project}" "${TODO_FILE}" | grep -c "${TERMS}")
+  # TODOTXT_VERBOSE=${OLD_TODOTXT_VERBOSE}
+  if [[ "${VALID_TERM}" -eq 0 ]]; then
+    echo "      \"${TERMS}\" not found in project \"${project}\" in todo.txt"
     usage
     exit 1
   fi
 done
 
-# if we have no projects and terms not in todo.txt error
-if [[ -z "${PROJECTS}" ]] && [[ -n "${TERMS}" ]]; then
-  OLD_TODOTXT_VERBOSE=${TODOTXT_VERBOSE:-1}
-  TODOTXT_VERBOSE=0 VALID_TERM=$(_list "${TODO_FILE}" "" "${TERMS}" | wc -l)
-  TODOTXT_VERBOSE=${OLD_TODOTXT_VERBOSE}
-  if [[ "${VALID_TERM}" -eq 0 ]]; then
-    echo "      \"${TERMS}\" not found in todo.txt"
-    usage
-    exit 1
-  fi
-fi
-
-# If we have no valid projects
+# If we have no projects or terms, set to all projects
 if [[ -z "${PROJECTS}" ]] && [[ -z "${TERMS}" ]]; then
-  PROJECTS=$(grep -o '[^ ]*+[^ ]\+' "$TODO_FILE" | sort -u | sed 's/^+//g' )
-  ((FOUND+=1))
+  PROJECTS=$("${TODO_FULL_SH}" listproj |sed 's/+//g')
 fi
 
 # Show projects in alphabetical order and todo items in priority order
diff --git a/actions/rename/projectrename b/actions/rename/projectrename
--- a/actions/rename/projectrename
+++ b/actions/rename/projectrename
@@ -17,55 +17,45 @@ usage() {
 	echo "      If no ITEM# given the rename all instances of old project"
 }
 
-# Function to take PROJECT and standardize
-_project_fix () {
-  INPUT="$1"
-  if [[ ${INPUT} =~ ^\+ ]]; then
-    NOTE="${INPUT##+}"
-  else
-    NOTE="${INPUT}"
+die () {
+  if [[ -n $* ]]; then
+    echo -e "$*"
   fi
-  echo "${NOTE}"
+  usage
+	exit 1
 }
 
-# Remove action
-shift
-
-# tests
-if [[ "${1}" = "usage" ]] || [[ "${1}" = "-h" ]]; then
+# Usage for todo.sh help or remove action
+if [[ "${1}" = "usage" ]] || [[ "${2}" = "usage" ]]; then
   usage
-  exit
-elif [[ $# -lt 2 ]]; then
-  echo "   Not enough options"
-  usage
-  exit 1
+	exit
+elif [[ "${1}" = "$(basename "$0")" ]]; then
+  shift
 fi
 
-OLDPROJECT=$(_project_fix "$1");shift
-NEWPROJECT=$(_project_fix "$1");shift
+if [[ $# -lt 2 ]]; then
+  die "      Not enough options"
+fi
+
+OLDPROJECT=${1/#+/};shift
+NEWPROJECT=${1/#+/};shift
 ITEM="$*"
 
 # Check our ITEM# are numeric
 if [[ -n "${ITEM}" ]] && ! [[ ${ITEM} =~ ^[0-9\ ]+$ ]]; then
-  echo "    ITEM# should be a LINE number"
-  usage
-  exit 1
+  die "      ITEM# should be a LINE number"
 fi
 
 # do we have that project in the todofile?
 if [[ "$(grep -c "${OLDPROJECT}\>" "${TODO_FILE}")" -eq 0 ]]; then
-  echo "    Cannot find project ${OLDPROJECT}"
-  usage
-  exit 1
+  die "      Cannot find project ${OLDPROJECT}"
 fi
 
 # Check OLDPROJECT is found in ITEM#
 for item in ${ITEM}; do
   LINE=$(sed -n "${item}p" "${TODO_FILE}")
   if [[ -n "${item}" ]] && ! [[ "${LINE}" =~ \+${OLDPROJECT} ]]; then
-    echo "    Cannot find project ${OLDPROJECT} in line number ${ITEM}"
-    usage
-    exit 1
+    die "      Cannot find project ${OLDPROJECT} in line number ${ITEM}"
   fi
 done
 
