feat(usage): Usage for action and subaction
* Allow usage for action and more detailed for subactions

diff --git a/actions/notes/notes b/actions/notes/notes
--- a/actions/notes/notes
+++ b/actions/notes/notes
@@ -12,39 +12,18 @@
 #===============================================================================
 
 usage () {
-	echo "    $(basename "$0") [add|archive]"
-	echo "      add [ITEMS] [NOTESFILE]"
-  echo "        Add NOTESFILE in ITEMS"
-	echo "      archive"
-  echo "        Archive any notesfile not in todo.txt"
-  echo "      cat"
-  echo "        Show contents of notesfile"
-  echo "      edit"
-  echo "        Edit a notesfile, use notes list to fine notesfiles"
-  echo "      grep"
-  echo "        List notesfiles that match a regex"
-  echo "      list"
-  echo "        Show all notes in todo.txt"
-  echo "      listarchived"
-  echo "        Show all archived notes"
-  echo "      rename"
-  echo "        Rename notesfile"
-  echo "      unarchive"
-  echo "        Move an archived note back to current"
+	echo "    $(basename "$0") [add|archive|cat|edit|grep|list|listarchived|rename|unarchive]"
 }
 
 die () {
-	if [[ -n $* ]]; then
-		echo -e "$*"
-  fi
-	usage
+  [[ -f "${TODO_TMP_FILE}" ]] && rm -rf "${TODO_TMP_FILE}"
 	exit 1
 }
 
+find_editor () {
 # Find editor to use, if EDITOR already set use.
 # Else use debian and derivatives editor (alternatives auto set by OS)
 # finally if neither EDITOR nor alternative set default to vi
-find_editor () {
   if [[ -n ${EDITOR} ]]; then
     true
 	elif [[ -L /usr/bin/editor ]]; then
@@ -55,9 +34,17 @@ find_editor () {
   echo "${EDITOR}"
 }
 
+todo_tmp () {
+  # Create file from todo and 'tickled' files if required
+  cat "${TODO_FILE}" > "${TODO_TMP_FILE}"
+  if [ -n "${TICKLER_DIR}" ]; then
+    find "${TICKLER_DIR}" -mindepth 2 -type f -size 1 -exec cat {} \; >>"${TODO_TMP_FILE}"
+  fi
+}
+
 # Usage for todo.sh help or remove action
 # Remove notes todo.txt action name
-if [[ "${2}" = "usage" ]] || [[ "${3}" = "usage" ]]; then
+if [[ "${2}" =~ (usage|help|--help) ]] || [[ "${3}" =~ (usage|help|--help) ]]; then
 	usage
 	exit
 elif [[ "${1}" = "$(basename "$0")" ]]; then
@@ -66,80 +53,77 @@ elif [[ "${1}" = "$(basename "$0")" ]]; then
   shift
 fi
 
-PRE="$(basename "${TODO_FILE}")"; PRE=${PRE/%\.txt/}
+if ! [[ "${action}" =~ (add|archive|cat|edit|grep|list|listarchived|rename|unarchive) ]]; then
+  usage
+fi
 
 # Check notes and archive exist
 mkdir -p "${TODO_DIR}/notes/archive" || exit 1
 cd "${TODO_DIR}/notes" || exit 1
 
+PRE="$(basename "${TODO_FILE}")"; PRE=${PRE/%\.txt/}
+NOTES=$(find . -maxdepth 1 -name "${PRE}*txt" -printf '%P\n')
+TODO_TMP_FILE="${TODO_TMP_FILE:-${TODO_DIR}/todo.tmp}"
+
 _add () {
-  # Check notes and item number exist
+  localUsage () {
+    echo "    $(basename "$0") ${action} [ITEMS] [NOTESFILE]"
+    echo "      append NOTESFILE to ITEMS and edit NOTESFILE if new"
+  }
+
   if [[ "$#" -lt 2 ]]; then
     if ! [[ "$1" =~ ^[0-9]+$ ]]; then
-      die "      No item given"
-    elif ! [[ "$2" =~ ^[0-9]+$ ]]; then
-      die "      No notesfile given"
+      echo "      No item given"
+      localUsage
+      die
     fi
   fi
-
-  # Set notes file from last argument and remove last argument
-  # this leaves items which we test later
-  NOTES_FILE="${!#}"
-  NOTES_FILE="${NOTES_FILE/#note:/}"
+  # Set notes file from last argument and remove from arguments
+  # this leaves only items which we test later
+  NOTES_FILE=${!##note:}
   set -- "${@:1:$(($#-1))}"
-  NOTES=$(find . -maxdepth 1 -name "${PRE}*txt" -printf '%P\n')
-
-  # If our enotes file is just numbers we didn't get given one
+  # If our notes file is just numbers we didn't get given one
   if [[ "${NOTES_FILE}" =~ ^[0-9]+$ ]]; then
-    die "      No notesfile given"
-  fi
-
-  # Can we edit after addition?
-  # Only set if file new to todo.txt and note doesn't exist
-  # Also check we have notesedit addon installed
-  if [[ "${NOTE_ADD_EDIT}" = "OFF" ]]; then
-    if [[ $(grep -c "${NOTES_FILE}" "${TODO_FILE}") -eq 0 ]] && \
-      ! [[ -f "${TODOTXT_DIR}/notes/${PRE}-${NOTES}.txt" ]] && \
-      [[ $(${TODO_FULL_SH} listaddons | grep -c ^notesedit$) -eq 1 ]]; then
-      EDIT_FILE=1
-    fi
+    echo "      No notesfile given"
+    localUsage
+    die
   fi
 
   # Are items in the file?
   # shellcheck disable=SC2048
   for item in $*; do
     if [[ ${item} -gt $(wc -l "${TODO_FILE}" | cut -f 1 -d " ") ]]; then
-      die "      No item ${item}"
+      echo "      ITEM ${item} not in todo file"
+      localUsage
+      die
+    elif ! [[ "${item}" =~ ^[0-9]+$ ]]; then
+      echo " ITEM is not a number"
+      localUsage
+      die
+    else
+      "${TODO_FULL_SH}" append "${item}" "note:${NOTES_FILE}"
+      echo "$(getPrefix "${TODO_FILE}"): note:${NOTES_FILE} added to item ${item}"
     fi
   done
 
-  # Use built in append action to add notesfile to each item, testing as we go
-  # shellcheck disable=SC2048
-  for item in $*; do
-    # Test we have an item number
-    if ! [[ "${item}" =~ ^[0-9]+$ ]]; then
-      die " ITEM is not a number"
-    fi
-    "${TODO_FULL_SH}" append "${item}" "note:${NOTES_FILE}"
-    echo "$(getPrefix "${TODO_FILE}"): note:${NOTES_FILE} added to item ${item}"
-  done
-
-  # If our tests allow open file for editing
-  if [[ "${EDIT_FILE}" = 1 ]]; then
+  # Can we edit after addition?
+  # Only set if file new to todo.txt and note doesn't exist
+  # Also check we have notesedit addon installed
+  if [[ "${NOTE_ADD_EDIT}" = "OFF" ]] && \
+    [[ $(grep -c "${NOTES_FILE}" "${TODO_FILE}") -eq 0 ]] && \
+    ! [[ -f "${TODOTXT_DIR}/notes/${PRE}-${NOTES}.txt" ]] && \
+    [[ $(${TODO_FULL_SH} listaddons | grep -c ^notesedit$) -eq 1 ]]; then
     "${TODO_FULL_SH}" notesedit "note:${NOTES_FILE}"
   fi
 }
 
 _archive (){
-  # construct file name
-  TODO_TMP_FILE="${TODO_TMP_FILE:-${TODO_DIR}/todo.tmp}"
-  NOTES=$(find . -maxdepth 1 -name "${PRE}-*txt" -printf '%P\n')
+  localUsage () {
+    echo "    $(basename "$0") ${action}"
+    echo "      Archive NOTESFILE not in todo.txt"
+  }
 
-  # Create file from todo and 'tickled' files
-  cat "${TODO_FILE}" > "${TODO_TMP_FILE}"
-  if [[ -n "${TICKLER_DIR}" ]] && [[ -d "${TICKLER_DIR}" ]]; then
-    find "${TICKLER_DIR}" -mindepth 2 -type f -size 1 -exec cat {} \; >> "${TODO_TMP_FILE}"
-  fi
+  todo_tmp
 
   # for each file, remove $PRE and see if its in todo or 'tickled' files
   for i in ${NOTES} ; do
@@ -148,11 +132,16 @@ _archive (){
     NUM_NOTE=$(grep -c "\bnote:${NOTE_FILE}\b" "${TODO_TMP_FILE}")
     if [[ "${NUM_NOTE}" -eq 0 ]] ;then
       cat "${TODO_DIR}/notes/${PRE}-${NOTE_FILE}.txt" >> \
-        "${TODO_DIR}/notes/archive/${PRE}-${NOTE_FILE}.$(date +%s).txt" || 
-        die "      unable to create archive file" && \
-      rm "${TODO_DIR}/notes/${PRE}-${NOTE_FILE}.txt"
+        "${TODO_DIR}/notes/archive/${PRE}-${NOTE_FILE}.$(date +%s).txt"
       echo "$(getPrefix): Archived note:${NOTE_FILE}"
       ((RETURN+=1)) 
+      if [[ $? -eq 1 ]]; then
+        echo "      unable to create archive file"
+        localUsage
+        die
+      else
+        rm "${TODO_DIR}/notes/${PRE}-${NOTE_FILE}.txt"
+      fi
     fi
   done
 
@@ -166,60 +155,78 @@ _archive (){
 }
 
 _cat (){
+  localUsage () {
+    echo "    $(basename "$0") ${action}"
+    echo "      Archive NOTESFILE not in todo.txt"
+  }
+
   if [[ $# -lt 1 ]]; then
-    die "      No notes file"
+    echo "      No notes file"
+    localUsage
+    die
   fi
 
-  NOTE_FILE="${1/#note:/}"; shift
+  NOTES_FILE="${1/#note:/}"; shift
 
-  if  [[ $(grep -c "${NOTE_FILE}" "${TODO_FILE}") -lt 1 ]]; then
-    die "      Notes file ${NOTE_FILE} not in todo.txt file,\n      use listnotes to find notes files"
+  if  [[ $(grep -c "${NOTES_FILE}" "${TODO_FILE}") -lt 1 ]]; then
+    echo "      Notes file ${NOTES_FILE} not in todo.txt file,"
+    echo "      use listnotes to find notes files"
+    localUsage
+    die
   fi
 
-  if [ -e "${TODO_DIR}/notes/${PRE}-${NOTE_FILE}.txt" ]; then
-    cat "${TODO_DIR}/notes/${PRE}-${NOTE_FILE}.txt" 2> /dev/null || \
-      die "    Unable to find or show ${PRE}-${NOTE_FILE}.txt"
-  fi
-}
-
-_edit () {
-  NOTE_FILE="${1/#note:/}"; shift
-  TODO_TMP_FILE="${TODO_TMP_FILE:-${TODO_DIR}/todo.tmp}"
-  EDITOR=$(find_editor)
-
-  if [[ -z "${NOTE_FILE}" ]]; then
-    die "      No notes file"
-  elif [[ $(grep -c "note:${NOTE_FILE}" "${TODO_FILE}") -eq 0 ]]; then
-    die "      No such notes file, use listnotes to find notes files"
-  fi
-
-  # Create file from todo and 'tickled' files
-  cat "${TODO_FILE}" > "${TODO_TMP_FILE}"
-  if [ -n "${TICKLER_DIR}" ]; then
-    find "${TICKLER_DIR}" -mindepth 2 -type f -size 1 -exec cat {} \; >>"${TODO_TMP_FILE}"
-  fi
-
-  # If file exists edit it else check listnotes for pointer then edit 
-  if [ -e "${TODO_DIR}/notes/${PRE}-${NOTE_FILE}.txt" ]; then
-    "${EDITOR}" "${TODO_DIR}/notes/${PRE}-${NOTE_FILE}.txt"
-  else
-    # If note link in todo.txt exists then edit
-    # shellcheck disable=SC2046,SC2086
-    NUM_ENOTE=$(grep -c "[^ ]*enote:${NOTE_FILE}[^ ]\+" "${TODO_TMP_FILE}")
-    if [ "${NUM_ENOTE}" -ge 1 ] ; then
-      "${EDITOR}" "${TODO_DIR}/notes/${PRE}-${NOTE_FILE}.txt"
-      [[ -f "${TODO_TMP_FILE}" ]] && rm -rf "${TODO_TMP_FILE}"
+  if [ -e "${TODO_DIR}/notes/${PRE}-${NOTES_FILE}.txt" ]; then
+    if ! cat "${TODO_DIR}/notes/${PRE}-${NOTES_FILE}.txt" 2> /dev/null; then
+      echo "    Unable to find or show ${PRE}-${NOTES_FILE}.txt"
+      localUsage
+      die
     fi
   fi
 }
 
-_grep () {
-  if [[ -z "$1" ]]; then
-    die "    No TERM"
+_edit () {
+  localUsage () {
+    echo "    $(basename "$0") ${action}"
+    echo "      Edit notes file, \$EDITOR."
+    echo "      use listnotes to get list of notes files"
+  }
+
+  NOTES_FILE="${1/#note:/}"; shift
+  EDITOR=$(find_editor)
+
+  if [[ -z "${NOTES_FILE}" ]]; then
+    echo "      No notes file"
+    localUsage
+    die
+  elif [[ $(grep -c "note:${NOTES_FILE}" "${TODO_FILE}") -eq 0 ]]; then
+    echo "      No such notes file, use listnotes to find notes files"
+    localUsage
+    die
   fi
 
-  cd "${TODO_DIR}/notes/" || exit 1
-  NOTES="$(find -- * -maxdepth 0 -name "${PRE}-*txt" -printf "%f\n")"
+  todo_tmp
+
+  # If file or note:file exists edit
+  NUM_ENOTE=$(grep -c "[^ ]*enote:${NOTES_FILE}[^ ]\+" "${TODO_TMP_FILE}")
+  if [[ -e "${PRE}-${NOTES_FILE}.txt" ]] || [[ "${NUM_ENOTE}" -ge 1 ]]; then
+    "${EDITOR}" "${PRE}-${NOTES_FILE}.txt"
+  fi
+  [[ -f "${TODO_TMP_FILE}" ]] && rm -rf "${TODO_TMP_FILE}"
+}
+
+_grep () {
+  localUsage () {
+    echo "    $(basename "$0") ${action} -a [TERM...]"
+    echo "      List notes that contain a TERM within them"
+    echo "      -a show archived notes"
+  }
+
+  if [[ -z "$1" ]]; then
+    echo "    No TERM"
+    localUsage
+    die
+  fi
+
   ARCHIVED="$(find -- archive/* -name "${PRE}-*.txt" -printf "%p\n")"
   if [[ "$1" = "-a" ]]; then
     ARCHIVE=1; shift
@@ -269,29 +276,30 @@ _grep () {
 }
 
 _list () {
-  TODO_TMP_FILE="${TODO_TMP_FILE:-${TODO_DIR}/todo.tmp}"
+  localUsage () {
+    echo "    $(basename "$0") ${action} -a [TERM...]"
+    echo "      List notes"
+    echo "      -a show archived notes"
+  }
 
-  # Create file from todo and 'tickled' files
-  cat "${TODO_FILE}" > "${TODO_TMP_FILE}"
-    if [ -n "${TICKLER_DIR}" ]; then
-    find "${TICKLER_DIR}" -mindepth 2 -type f -size 1 -exec cat {} \; >> "${TODO_TMP_FILE}"
-  fi
+  todo_tmp
 
   if [[ $(grep -o '\bnote\:[a-zA-Z0-9\._-]*' "${TODO_TMP_FILE}" | grep -c "$*") -gt 0 ]]; then
     grep -o '\bnote\:[a-zA-Z0-9\._-]*' "${TODO_TMP_FILE}" | grep "$*" | sort -u
     [[ -f "${TODO_TMP_FILE}" ]] && rm -rf "${TODO_TMP_FILE}"
   else
-    [[ -f "${TODO_TMP_FILE}" ]] && rm -rf "${TODO_TMP_FILE}"
-    die "      No notes with the term \"$*\""
+    echo "      No notes with the term \"$*\""
+    localUsage
+    die
   fi
 }
 
 _listarchived () {
-  TODO_TMP_FILE="${TODO_TMP_FILE:-${TODO_DIR}/todo.tmp}"
-
-  # Check notes and archive exist
-  mkdir -p "${TODO_DIR}/notes/archive/" || exit 1
-  cd "${TODO_DIR}/notes/archive/" || exit 1
+  localUsage () {
+    echo "    $(basename "$0") ${action} [TERM...]"
+    echo "      List archived notes"
+  }
+  cd archive || exit 1
 
   # Find a list of files
   find . -name "${PRE}-*txt" -printf '%P\n'  | grep "^${PRE}-" | \
@@ -301,21 +309,27 @@ _listarchived () {
     grep "$*" "${TODO_TMP_FILE}"
     [[ -f "${TODO_TMP_FILE}" ]] && rm -rf "${TODO_TMP_FILE}"
   else
-    [[ -f "${TODO_TMP_FILE}" ]] && rm -rf "${TODO_TMP_FILE}"
-    die "      No notes with the term \"$*\""
+    echo "      No notes with the term \"$*\""
+    localUsage
+    die
   fi
 }
 
 _rename () {
+  localUsage () {
+    echo "    $(basename "$0") ${action} [ORIGINAL_NOTESFILE] [NEW_NOTESFILE]"
+    echo "      rename ORIGINAL_NOTESFILE to NEW_NOTESFILE"
+    echo "      the note: is not required, but added"
+  }
+
   if [[ "$#" -ne 2 ]]; then
-    die "    check number of options"
+    echo "    check number of options"
+    localUsage
+    die
   fi
 
-  OLD_FILE=${1##note:}
-  NEW_FILE=${2##note:}
-  NOTES_DIR="${TODO_DIR}/notes"
-
-  cd "${NOTES_DIR}" || exit 1
+  OLD_FILE=${1/#note:/}
+  NEW_FILE=${2/#note:/}
 
   # Move the note
   if [[ "$(grep -c "${OLD_FILE}" "${TODO_FILE}")" -ge 1 ]]; then
@@ -330,12 +344,14 @@ _rename () {
     ((UPDATE+=1))
   fi
   if [[ -z "${UPDATE}" ]]; then
-    die "    ${OLD_FILE} is not a current note, use listnotes to find notes."
+    echo "    ${OLD_FILE} is not a current note, use listnotes to find notes."
+    localUsage
+    die
   fi
 
   # rename OLD_FILE
-  if [[ -f "${NOTES_DIR}/${PRE}-${OLD_FILE}.txt" ]]; then
-    mv "${NOTES_DIR}/${PRE}-${OLD_FILE}.txt" "${NOTES_DIR}/${PRE}-${NEW_FILE}.txt"
+  if [[ -f "${PRE}-${OLD_FILE}.txt" ]]; then
+    mv "${PRE}-${OLD_FILE}.txt" "${PRE}-${NEW_FILE}.txt"
   fi
 
   # Test for OLD_FILE in 'tickled' files and rename
@@ -345,42 +361,47 @@ _rename () {
       sed -i "s/note:${OLD_FILE}\b/note:${NEW_FILE}" "${FILE}"
       echo "$(getPrefix): Changed note:${OLD_FILE} to note:${NEW_FILE} in tickled file ${FILE}"
     done
-      mv "${NOTES_DIR}/${OLD_FILE}.txt" "${NOTES_DIR}/${NEW_FILE}.txt"
   fi
 }
 
 _unarchive () {
-  cd "${TODO_DIR}/notes/archive/" || exit 1
+  localUsage () {
+    echo "    $(basename "$0") ${action} [NOTESFILE]"
+    echo "      unarchive notes files, this brings back the last"
+  }
 
-  FILE=${1##note:}; shift
-  DATE_FILE=$(find -- * -name "${PRE}-${FILE}.*.txt" -type f -printf "%T@ %p\n"  2> /dev/null | sort -n | cut -f 2 -d " "  | tail -n 1)
+  cd archive || exit 1
+
+  NOTES_FILE=${1/#note:/}; shift
+  DATE_FILE=$(find -- * -name "${PRE}-${NOTES_FILE}.*.txt" -type f -printf "%T@ %p\n"  2> /dev/null | sort -n | cut -f 2 -d " "  | tail -n 1)
   ARC_FILE="${TODO_DIR}/notes/archive/${DATE_FILE}"
-  NOTES_FILE="${TODO_DIR}/notes/${PRE}-${FILE}.txt"
-  TODO_TMP_FILE="${TODO_TMP_FILE:-${TODO_DIR}/todo.tmp}"
+
+  todo_tmp
 
   if [[ -z "${DATE_FILE}" ]]; then
-    die "      No archived notes file named ${FILE}. Use listarchivedenotes to find them"
+    echo "      No archived notes file named ${NOTES_FILE}. Use notes listarchived to find them"
+    localUsage
+    die
+  elif [[ "$(grep -c "\bnote:${NOTES_FILE}\b" "${TODO_TMP_FILE}")" -eq 0 ]] ;then
+    echo "      Note file ${NOTES_FILE} not mentioned in todo"
+    echo "      use listnotes to find them"
+    localUsage
+    die
   fi
 
-  # Does the notes file exist? i.e  mentioned in todo/tickled file?
-  cat "${TODO_FILE}" > "${TODO_TMP_FILE}"
-  if [[ -n ${TICKLER_DIR} ]] && [[ -d ${TICKLER_DIR} ]]; then
-    find "${TICKLER_DIR}" -mindepth 2 -type f -size 1 -exec cat {} \; >> "${TMP_FILE}"
-  fi
-  if [[ "$(grep -c "\bnote:${FILE}\b" "${TODO_TMP_FILE}")" -eq 0 ]] ;then
-    die "      Note file ${FILE} not mentioned in todo\n      use listnotes to find them"
-  fi
-  [[ -f "${TODO_TMP_FILE}" ]] && rm -rf "${TODO_TMP_FILE}"
-
-  cp "${ARC_FILE}" "${NOTES_FILE}"
+  cp "${ARC_FILE}" "${TODO_DIR}/notes/${PRE}-${NOTES_FILE}.txt"
   if [[ "$?" -eq 1 ]]; then
-    die "     Unable to move ${PRE}-${FILE}.txt to ${NO_DATE_FILE}.txt"
+    echo "     Unable to move ${PRE}-${NOTES_FILE}.txt to ${NO_DATE_FILE}.txt"
+    localUsage
+    die
   else
-    echo "$(getPrefix): Notes file ${PRE}-${FILE}.txt restored from newest archive"
+    echo "$(getPrefix): Notes file ${PRE}-${NOTES_FILE}.txt restored from newest archive"
   fi
+
+  [[ -f "${TODO_TMP_FILE}" ]] && rm -rf "${TODO_TMP_FILE}"
 }
 
-# what to do for each action
+# We actually want white space separated options so no quotes on our $@
 case ${action} in
   add)
     # shellcheck disable=SC2068
@@ -418,7 +439,7 @@ case ${action} in
     # shellcheck disable=SC2068
     _unarchive $@
   ;;
-  *) # This catches all cases that weren't previously listed. That's why it has the wildcard "*" operator.
+  *)
     usage
   ;;
 esac
